name: cadd-env
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- ensembl-vep=89.1=htslib1.4_1
- pysam=0.11.2.1=py27_0
- pyvcf=0.6.8=py27_0
- samtools=1.4.1=0
- numpy=1.13.0=py27_blas_openblas_200
- python=2.7.13=0
